export const TESTS_HAS_ERRORED = 'TESTS_HAS_ERRORED';
export const TESTS_IS_LOADING = 'TESTS_IS_LOADING';
export const TESTS_FETCH_DATA_SUCCESS = 'TESTS_FETCH_DATA_SUCCESS';
export const TESTS_IS_SAVING = 'TESTS_IS_SAVING';
export const TESTS_IS_LOADED = 'TESTS_IS_LOADED';

export const TESTS_ADD_TO_EDIT = 'TESTS_TO_EDIT';
export const TESTS_CURRENT_INDEX_QUESTION = 'TESTS_CURRENT_INDEX_QUESTION';
export const TESTS_CURRENT_INDEX = 'TESTS_CURRENT_INDEX';
export const TESTS_IS_IN_CREATION = 'TESTS_IS_IN_CREATION';
export const TESTS_INTERNAL_HAS_ERRORED = 'TESTS_INTERNAL_HAS_ERRORED';
export const TESTS_DATA_INTERNAL = 'TESTS_DATA_INTERNAL';
export const TESTS_CLEAR_DATA_INTERNAL = 'TESTS_CLEAR_DATA_INTERNAL';


export const QUESTIONS_INTERNAL_HAS_ERRORED = 'QUESTIONS_INTERNAL_HAS_ERRORED';
export const QUESTIONS_IS_IN_CREATION = 'QUESTIONS_IS_IN_CREATION';
export const QUESTIONS_DATA_INTERNAL = 'QUESTIONS_DATA_INTERNAL';
export const QUESTIONS_CLEAR_DATA = 'QUESTIONS_CLEAR_DATA';

export const OPTIONS_DATA_INTERNAL = 'OPTIONS_DATA_INTERNAL';
export const OPTIONS_SET_GOAL = 'OPTIONS_SET_GOAL';
export const OPTIONS_CLEAR_DATA = 'OPTIONS_CLEAR_DATA';